Updated test-unit.yml to comment a coverage report
Signed-off-by: Tanner Jones <alltechguyblog@gmail.com>

diff --git a/.github/workflows/test-unit.yml b/.github/workflows/test-unit.yml
--- a/.github/workflows/test-unit.yml
+++ b/.github/workflows/test-unit.yml
@@ -16,13 +16,12 @@ jobs:
       fail-fast: false
     steps:
       - uses: actions/checkout@v3
-        with:
-          fetch-depth: 1
+        with: { fetch-depth: 1 }
       - uses: actions/setup-go@v3
         with:
           go-version: "${{ matrix.go }}"
       - run: go version
-      - run: make test-unit-with-coverage
+      - run: make test-unit-with-coverage race=true
       - name: Upload coverage report
         uses: codecov/codecov-action@v1
         with:
@@ -30,16 +29,16 @@ jobs:
           file: coverage.out
       - name: Comment coverage report
         run: |
-          curl -sSfL https://codecov.io/bash | bash -s -- -Z -K -f coverage.out || echo "Codecov upload failed"
-        if: matrix.os == 'ubuntu-latest'
+          if [ "${{ matrix.os }}" == "ubuntu-latest" ]; then # will only run on ubuntu
+            curl -sSfL https://codecov.io/bash | bash -s -- -Z -K -f coverage.out || echo "Codecov upload failed"
+          fi      
 
   bench:
     name: Benchmarks
     runs-on: ubuntu-latest
     steps:
       - uses: actions/checkout@v3
-        with:
-          fetch-depth: 1
+        with: { fetch-depth: 1 }
       - uses: actions/setup-go@v3
         with:
           go-version: '1.x'
